# Generated by Django 5.2.11 on 2026-02-25 19:54

import apps.accounts.models.managers
import apps.accounts.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Principal",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("disabled_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("disabled_reason", models.CharField(blank=True, default="", max_length=255)),
                ("locked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_reason", models.CharField(blank=True, default="", max_length=255)),
                ("suspended_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("suspended_reason", models.CharField(blank=True, default="", max_length=255)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user", "User Account"),
                            ("service", "Service Account"),
                            ("api_client", "API Client"),
                            ("agent", "Agent"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[apps.accounts.validators.UsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional. Used for notifications and recovery.",
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Optional. Used for notifications and recovery.",
                        max_length=17,
                        validators=[apps.accounts.validators.PhoneNumberValidator()],
                        verbose_name="phone number",
                    ),
                ),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("display_name", models.CharField(blank=True, default="", max_length=150)),
                ("external_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("external_provider", models.CharField(blank=True, default="", max_length=50)),
                (
                    "passwordless_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether passwordless authentication (e.g., magic link) is enabled for this account.",
                    ),
                ),
                (
                    "security_stamp",
                    models.BigIntegerField(
                        default=0,
                        help_text="Bump to invalidate all sessions issued for this principal.",
                        verbose_name="security stamp",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disabled_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspended_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "principal",
                "verbose_name_plural": "principals",
                "db_table": "principals",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", apps.accounts.models.managers.PrincipalManager()),
            ],
        ),
        migrations.CreateModel(
            name="AgentAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Unique machine-readable identifier for this agent.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        db_index=True,
                        help_text='Classification of the agent (e.g., "llm", "workflow", "cron").',
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("allowed_scopes", models.JSONField(blank=True, default=list)),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object describing agent capabilities and feature flags.",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User principal who owns/manages this agent.",
                        limit_choices_to={"kind": "user"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_agent_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal",
                    models.OneToOneField(
                        help_text="Canonical principal for session ownership.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_accounts",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="APIClient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("client_id", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "client_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hashed client secret.  Never store plaintext.",
                        max_length=255,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("confidential", "Confidential"), ("public", "Public")],
                        default="confidential",
                        max_length=20,
                    ),
                ),
                ("redirect_uris", models.JSONField(blank=True, default=list)),
                ("allowed_scopes", models.JSONField(blank=True, default=list)),
                ("grant_types", models.JSONField(blank=True, default=list)),
                ("website_url", models.URLField(blank=True, default="")),
                ("terms_url", models.URLField(blank=True, default="")),
                ("privacy_url", models.URLField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User principal who owns/manages this API client.",
                        limit_choices_to={"kind": "user"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_api_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal",
                    models.OneToOneField(
                        help_text="Canonical principal for session ownership and stamp invalidation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_clients",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("service_name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("allowed_scopes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User principal who owns/manages this service account.",
                        limit_choices_to={"kind": "user"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_service_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal",
                    models.OneToOneField(
                        help_text="Canonical principal for session ownership.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_accounts",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("given_name", models.CharField(blank=True, default="", max_length=64)),
                ("family_name", models.CharField(blank=True, default="", max_length=64)),
                ("middle_name", models.CharField(blank=True, default="", max_length=64)),
                ("nickname", models.CharField(blank=True, default="", max_length=64)),
                ("picture_url", models.URLField(blank=True, default="")),
                ("gender", models.CharField(blank=True, default="", max_length=50)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, default="")),
                ("bio", models.TextField(blank=True, default="", max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "principal",
                    models.OneToOneField(
                        help_text="Canonical principal row for sessions, authentication, and lifecycle.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_accounts",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="principal",
            index=models.Index(fields=["kind"], name="principals_kind_128633_idx"),
        ),
        migrations.AddIndex(
            model_name="principal",
            index=models.Index(fields=["expires_at"], name="principals_expires_c5c2d6_idx"),
        ),
        migrations.AddIndex(
            model_name="principal",
            index=models.Index(fields=["deleted_at"], name="principals_deleted_fc86fa_idx"),
        ),
        migrations.AddIndex(
            model_name="agentaccount",
            index=models.Index(fields=["agent_type"], name="agent_accou_agent_t_78e7ac_idx"),
        ),
        migrations.AddIndex(
            model_name="agentaccount",
            index=models.Index(fields=["deleted_at"], name="agent_accou_deleted_ef8eec_idx"),
        ),
        migrations.AddIndex(
            model_name="apiclient",
            index=models.Index(fields=["client_id"], name="api_clients_client__52c9e3_idx"),
        ),
        migrations.AddIndex(
            model_name="apiclient",
            index=models.Index(fields=["owner"], name="api_clients_owner_i_bedd75_idx"),
        ),
        migrations.AddIndex(
            model_name="apiclient",
            index=models.Index(fields=["deleted_at"], name="api_clients_deleted_36eff8_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceaccount",
            index=models.Index(fields=["service_name"], name="service_acc_service_7be669_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceaccount",
            index=models.Index(fields=["deleted_at"], name="service_acc_deleted_1f460b_idx"),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(fields=["deleted_at"], name="user_accoun_deleted_943c53_idx"),
        ),
    ]
