# Generated by Django 5.2.11 on 2026-02-25 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("code_hash", models.CharField(max_length=128)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "backup_code_credentials",
                "indexes": [
                    models.Index(fields=["principal"], name="backup_code_princip_a3cd7f_idx"),
                    models.Index(fields=["status"], name="backup_code_status_ac2e16_idx"),
                    models.Index(fields=["deleted_at"], name="backup_code_deleted_60952b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "identifier",
                    models.CharField(
                        db_index=True, help_text="The identifier used (email, username, phone number).", max_length=255
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("invalid_credentials", "Invalid Credentials"),
                            ("account_locked", "Account Locked"),
                            ("account_disabled", "Account Disabled"),
                            ("mfa_required", "MFA Required"),
                            ("mfa_failed", "MFA Failed"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("auth_method", models.CharField(blank=True, default="", max_length=30)),
                ("ip_address", models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=500)),
                ("failure_reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "login_attempts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["principal", "result", "created_at"], name="login_attem_princip_c5c99e_idx"),
                    models.Index(fields=["identifier", "created_at"], name="login_attem_identif_2d20fd_idx"),
                    models.Index(fields=["ip_address", "created_at"], name="login_attem_ip_addr_f68fb5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MFAPendingAuthentication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "auth_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The primary auth method that was used (password, passwordless, etc.).",
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=500)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_pending_auths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mfa_pending_authentications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token_hash"], name="mfa_pending_token_h_1af30d_idx"),
                    models.Index(fields=["principal", "expires_at"], name="mfa_pending_princip_76c3d9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordCredential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("password_hash", models.CharField(max_length=128)),
                ("strength_score", models.PositiveSmallIntegerField(default=0)),
                ("is_compromised", models.BooleanField(default=False)),
                ("require_change", models.BooleanField(default=False)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_credentials",
                "indexes": [
                    models.Index(fields=["principal"], name="password_cr_princip_aae36c_idx"),
                    models.Index(fields=["status"], name="password_cr_status_46151f_idx"),
                    models.Index(fields=["deleted_at"], name="password_cr_deleted_e8caa1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "set_by",
                    models.CharField(
                        choices=[
                            ("user_change", "User Change"),
                            ("admin_reset", "Admin Reset"),
                            ("system_reset", "System Reset"),
                            ("initial", "Initial Registration"),
                        ],
                        default="user_change",
                        max_length=20,
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_history",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["principal", "created_at"], name="password_hi_princip_d3c090_idx")],
            },
        ),
        migrations.CreateModel(
            name="TOTPCredential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("secret", models.CharField(max_length=64)),
                ("algorithm", models.CharField(default="SHA1", max_length=10)),
                ("digits", models.PositiveSmallIntegerField(default=6)),
                ("period", models.PositiveSmallIntegerField(default=30)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "totp_credentials",
                "indexes": [
                    models.Index(fields=["principal"], name="totp_creden_princip_4c341e_idx"),
                    models.Index(fields=["status"], name="totp_creden_status_905a6d_idx"),
                    models.Index(fields=["deleted_at"], name="totp_creden_deleted_586abd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verify", "Email Verification"),
                            ("phone_verify", "Phone Verification"),
                            ("password_reset", "Password Reset"),
                            ("passwordless", "Passwordless Login"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("otp_hash", models.CharField(blank=True, default="", max_length=64)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("delivery_target", models.CharField(blank=True, default="", max_length=255)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "verification_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token_hash"], name="verificatio_token_h_e2f046_idx"),
                    models.Index(fields=["principal", "purpose"], name="verificatio_princip_17b82e_idx"),
                    models.Index(fields=["expires_at"], name="verificatio_expires_2a1de8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("credential_id", models.TextField(db_index=True, unique=True)),
                ("public_key", models.TextField()),
                ("sign_count", models.PositiveIntegerField(default=0)),
                ("aaguid", models.CharField(blank=True, default="", max_length=36)),
                ("transports", models.JSONField(blank=True, default=list)),
                ("backup_eligible", models.BooleanField(default=False)),
                ("backup_state", models.BooleanField(default=False)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "webauthn_credentials",
                "indexes": [
                    models.Index(fields=["principal"], name="webauthn_cr_princip_3e4ee2_idx"),
                    models.Index(fields=["status"], name="webauthn_cr_status_37ae45_idx"),
                    models.Index(fields=["deleted_at"], name="webauthn_cr_deleted_94a44d_idx"),
                ],
            },
        ),
    ]
