# Generated by Django 5.2 on 2026-02-24 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="backupcode",
            name="backup_code_user_id_5bdf7b_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginattempt",
            name="login_attem_user_id_9d23cc_idx",
        ),
        migrations.RemoveIndex(
            model_name="mfapendingauthentication",
            name="mfa_pending_user_id_52ac10_idx",
        ),
        migrations.RemoveIndex(
            model_name="passwordcredential",
            name="password_cr_user_id_170bbe_idx",
        ),
        migrations.RemoveIndex(
            model_name="passwordhistory",
            name="password_hi_user_id_f4f4ce_idx",
        ),
        migrations.RemoveIndex(
            model_name="totpcredential",
            name="totp_creden_user_id_25b10a_idx",
        ),
        migrations.RemoveIndex(
            model_name="verificationtoken",
            name="verificatio_user_id_895be8_idx",
        ),
        migrations.RemoveIndex(
            model_name="webauthncredential",
            name="webauthn_cr_user_id_7a1b97_idx",
        ),
        migrations.RenameField(
            model_name="backupcode",
            old_name="user",
            new_name="principal",
        ),
        migrations.RenameField(
            model_name="loginattempt",
            old_name="user",
            new_name="principal",
        ),
        migrations.RenameField(
            model_name="mfapendingauthentication",
            old_name="user",
            new_name="principal",
        ),
        migrations.RenameField(
            model_name="passwordcredential",
            old_name="user",
            new_name="principal",
        ),
        migrations.RenameField(
            model_name="passwordhistory",
            old_name="user",
            new_name="principal",
        ),
        migrations.RenameField(
            model_name="totpcredential",
            old_name="user",
            new_name="principal",
        ),
        migrations.RenameField(
            model_name="verificationtoken",
            old_name="user",
            new_name="principal",
        ),
        migrations.RenameField(
            model_name="webauthncredential",
            old_name="user",
            new_name="principal",
        ),
        migrations.AddIndex(
            model_name="backupcode",
            index=models.Index(fields=["principal"], name="backup_code_princip_a3cd7f_idx"),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(fields=["principal", "result", "created_at"], name="login_attem_princip_c5c99e_idx"),
        ),
        migrations.AddIndex(
            model_name="mfapendingauthentication",
            index=models.Index(fields=["principal", "expires_at"], name="mfa_pending_princip_76c3d9_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordcredential",
            index=models.Index(fields=["principal"], name="password_cr_princip_aae36c_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(fields=["principal", "created_at"], name="password_hi_princip_d3c090_idx"),
        ),
        migrations.AddIndex(
            model_name="totpcredential",
            index=models.Index(fields=["principal"], name="totp_creden_princip_4c341e_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationtoken",
            index=models.Index(fields=["principal", "purpose"], name="verificatio_princip_17b82e_idx"),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(fields=["principal"], name="webauthn_cr_princip_3e4ee2_idx"),
        ),
    ]
