# Generated by Django 5.2.11 on 2026-02-25 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("disabled_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("disabled_reason", models.CharField(blank=True, default="", max_length=255)),
                ("locked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_reason", models.CharField(blank=True, default="", max_length=255)),
                ("suspended_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("suspended_reason", models.CharField(blank=True, default="", max_length=255)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("authenticated_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("idle_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, help_text="When admin force-terminated this session", null=True),
                ),
                (
                    "logged_out_at",
                    models.DateTimeField(
                        blank=True, help_text="When user voluntarily logged out (can re-authenticate)", null=True
                    ),
                ),
                ("user_agent", models.CharField(blank=True, default="", max_length=500)),
                ("ip_first", models.GenericIPAddressField(blank=True, null=True)),
                ("ip_last", models.GenericIPAddressField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, default="", max_length=128)),
                ("device_fingerprint", models.CharField(blank=True, default="", max_length=255)),
                ("is_trusted_device", models.BooleanField(default=False)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("security_stamp_at_issue", models.BigIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disabled_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspended_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionCredential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("session_handle", "Session Handle"),
                            ("refresh_token", "Refresh Token"),
                            ("access_jti", "Access Token JTI"),
                            ("dpop_key", "DPoP Key"),
                            ("mtls_cert", "mTLS Cert"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("handle_hash", models.CharField(db_index=True, max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("family_id", models.UUIDField(blank=True, db_index=True, default=None, null=True)),
                ("parent_id", models.UUIDField(blank=True, db_index=True, default=None, null=True)),
                ("is_revoked", models.BooleanField(db_index=True, default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="user_sessions.authsession",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_credentials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="authsession",
            index=models.Index(fields=["principal", "last_seen_at"], name="auth_sessio_princip_c23797_idx"),
        ),
        migrations.AddIndex(
            model_name="authsession",
            index=models.Index(fields=["device_fingerprint"], name="auth_sessio_device__a3ef13_idx"),
        ),
        migrations.AddIndex(
            model_name="authsession",
            index=models.Index(fields=["deleted_at"], name="auth_sessio_deleted_040dab_idx"),
        ),
        migrations.AddIndex(
            model_name="sessioncredential",
            index=models.Index(fields=["session", "kind"], name="session_cre_session_81189e_idx"),
        ),
        migrations.AddIndex(
            model_name="sessioncredential",
            index=models.Index(fields=["kind", "handle_hash"], name="session_cre_kind_85d6cf_idx"),
        ),
        migrations.AddIndex(
            model_name="sessioncredential",
            index=models.Index(fields=["expires_at"], name="session_cre_expires_be4d1c_idx"),
        ),
        migrations.AddIndex(
            model_name="sessioncredential",
            index=models.Index(fields=["deleted_at"], name="session_cre_deleted_5858fa_idx"),
        ),
    ]
