# Generated by Django 5.2.11 on 2026-02-25 19:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_id", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("restore", "Restore"),
                            ("undo", "Undo"),
                            ("redo", "Redo"),
                            ("bulk_create", "Bulk Create"),
                            ("bulk_update", "Bulk Update"),
                            ("bulk_delete", "Bulk Delete"),
                            ("bulk_restore", "Bulk Restore"),
                            ("archive", "Archive"),
                            ("unarchive", "Unarchive"),
                            ("merge", "Merge"),
                            ("split", "Split"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("snapshot", models.JSONField(blank=True, null=True)),
                ("snapshot_compressed", models.BinaryField(blank=True, null=True)),
                ("delta", models.JSONField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("parent_checksum", models.CharField(blank=True, default="", max_length=128)),
                (
                    "compression_algorithm",
                    models.CharField(
                        blank=True,
                        choices=[("none", "None"), ("zlib", "Zlib"), ("gzip", "Gzip"), ("brotli", "Brotli")],
                        max_length=20,
                    ),
                ),
                ("original_size", models.PositiveIntegerField(blank=True, null=True)),
                ("compressed_size", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("comment", models.TextField(blank=True, default="")),
                ("backends_pending", models.JSONField(blank=True, default=list)),
                ("backends_dispatched", models.JSONField(blank=True, default=dict)),
                ("backends_failed", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="auditing.event",
                    ),
                ),
                (
                    "target_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensating_events",
                        to="auditing.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "db_table": "auditing_event",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["actor", "created_at"], name="auditing_event_actor_cat_idx")],
            },
        ),
    ]
